name: kokage
version: 0.1.0.0
github: "pe200012/kokage"
license: BSD-3-Clause
author: "pe200012"
maintainer: "1326263755@qq.com"
copyright: "2025 pe200012"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: ukagaka baseware for Linux

# Cabal flags for optional features
flags:
  layer-shell:
    description: Enable Wayland layer-shell support (requires gtk4-layer-shell C library)
    manual: true
    default: false

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - bytestring
  - iconv # Shift-JIS encoding support
  - vector
  - megaparsec # parsing
  - gi-gtk4 # GTK4 bindings (4.0.8 from extra-deps)
  - gi-gdk4 # GTK4 Gdk
  - gi-pango # Pango text rendering (for balloon text wrapping)
  - gi-pangocairo # PangoCairo for text rendering on Cairo surfaces
  - gi-gdkx114 # GDK X11 bindings for always-on-top
  - gi-cairo # Cairo GI bindings (for Region type)
  - gi-cairo-render # Cairo rendering
  - gi-cairo-connector
  - gi-gdkpixbuf # image loading
  - gi-gio
  - gi-glib
  - haskell-gi-base # GI base types
  - X11 # X11 bindings for window hints
  - filepath
  - directory
  - mtl
  - transformers
  - process # Wine subprocess management
  - base64-bytestring # Base64 encoding for IPC
  - time # Time for debugging
  - reactive-banana # FRP
  - reactive-banana-gi-gtk # FRP with GTK
  - zip-archive # NAR/ZIP archive handling
  - text-builder # Efficient text building for SHIORI protocol

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  when:
    - condition: flag(layer-shell)
      dependencies:
        - gi-gtk4-layer-shell
      cpp-options: -DLAYER_SHELL

executables:
  kokage:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - kokage
      - optparse-applicative

  shiori-test:
    main: Main.hs
    source-dirs: app-shiori-test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - kokage
      - time

tests:
  kokage-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - hspec-discover
    dependencies:
      - kokage
      - hspec
      - hspec-megaparsec
      - temporary
