# Stack configuration for kokage

resolver: lts-24.23
compiler: ghc-9.12.2

packages:
  - .

extra-deps:
  - gi-gtk-4.0.8
  - gi-gdk-4.0.7
  - gi-gdkpixbuf-2.0.31
  - gi-cairo-render-0.1.2
  - gi-gio-2.0.34
  - gi-glib-2.0.29
  - gi-gobject-2.0.31
  - gi-cairo-1.0.29
  - haskell-gi-0.26.17
  - haskell-gi-base-0.26.9
  - haskell-gi-overloading-1.0
  - reactive-banana-gi-gtk-0.4.1.0

allow-newer: true
allow-newer-deps:
  - reactive-banana-gi-gtk
