{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Kokage.Animation
  ( -- * Animation State
    ActiveAnim(..)
  , AnimationState(..)
  , newAnimationState
    -- * Animation Logic
  , tickAnimations
  , compositeAnimation
    -- * Animation Control
  , invokeRunonce
  , invokeAlways
  , invokeAnimation
  , invokeYenE
  , invokeTalk
  , stopAnimation
  , stopAllAnimations
  , clearAnimations
    -- * Bind (着せ替え) Control
  , toggleBind
  , getBindState
  , setBindState
  , getEnabledBinds
    -- * Exclusive Animation Support
  , isExclusiveRunning
  , processQueue
    -- * Re-export cache type for callers
  , ImageCache
  ) where

import           Control.Monad     ( foldM, foldM_, unless, when )

import           Data.IORef        ( IORef )
import           Data.Int          ( Int32 )
import           Data.List         ( sortBy, (!!) )
import           Data.Map.Strict   ( Map )
import qualified Data.Map.Strict   as Map
import           Data.Maybe        ( catMaybes )
import           Data.Ord          ( comparing )
import           Data.Set          ( Set )
import qualified Data.Set          as Set

import qualified GI.GdkPixbuf      as Pixbuf

import           Kokage.ImageCache ( ImageCache, getCachedImage, newImageCache )
import           Kokage.Surface    ( compositeSurface, findSurfaceById, loadDefaultSurface )

import           System.Random     ( randomRIO )

import           Types.Ghost       ( Animation(..)
                                   , AnimationInterval(..)
                                   , AnimationOption(..)
                                   , AnimationPattern(..)
                                   , DrawMethod(..)
                                   , Shell(..)
                                   , SurfaceDefinition(..)
                                   )

-- | Commands generated by animation patterns to control other animations.
data AnimCommand
  = CmdStart !Int       -- ^ Start animation with given ID
  | CmdStop !Int        -- ^ Stop animation with given ID
  | CmdStartAll [ Int ]   -- ^ Start all animations with given IDs (parallel)
  | CmdStopAll [ Int ]    -- ^ Stop all animations with given IDs
  deriving ( Show, Eq )

-- | A currently running animation instance.
data ActiveAnim
  = ActiveAnim
  { aaDef       :: !Animation         -- ^ The animation definition
  , aaStepIndex :: !Int               -- ^ Current pattern index
  , aaWaitLeft  :: !Int               -- ^ Time remaining for current step (ms)
  , aaVisual    :: !Bool              -- ^ Whether the current step is visual (has valid surfaceId)
  , aaLooping   :: !Bool              -- ^ Whether this animation should loop (for Always interval)
  }
  deriving ( Show, Eq )

-- | State container for character animations.
data AnimationState
  = AnimationState
  { asActiveAnims   :: !(IORef [ ActiveAnim ])       -- ^ Currently active animations
  , asBasePixbuf    :: !(IORef (Maybe Pixbuf.Pixbuf)) -- ^ The base surface image (without animations)
  , asPeriodicState :: !(IORef (Map Int Int))      -- ^ State for periodic animations (AnimID -> Accumulated Time ms)
  , asImageCache    :: !ImageCache                 -- ^ LRU cache for animation overlay images
  , asBindState     :: !(IORef (Set Int))          -- ^ Enabled bind animation IDs (着せ替え)
  , asExclusiveAnim :: !(IORef (Maybe Int))        -- ^ Currently running exclusive animation ID
  , asAnimQueue     :: !(IORef [ Animation ])        -- ^ Queue for animations waiting for exclusive to finish
  }

-- | Create a new empty animation state.
newAnimationState :: IO AnimationState
newAnimationState = do
  animsRef <- newIORef []
  baseRef <- newIORef Nothing
  periodicRef <- newIORef Map.empty
  cache <- newImageCache 64  -- Cache up to 64 overlay images
  bindRef <- newIORef Set.empty
  exclusiveRef <- newIORef Nothing
  queueRef <- newIORef []
  return
    AnimationState
    { asActiveAnims   = animsRef
    , asBasePixbuf    = baseRef
    , asPeriodicState = periodicRef
    , asImageCache    = cache
    , asBindState     = bindRef
    , asExclusiveAnim = exclusiveRef
    , asAnimQueue     = queueRef
    }

-- | Process one tick (typically 50ms) of animations.
-- Updates the list of active animations and determines if a redraw is needed.
-- Also triggers new animations based on intervals (random, etc.).
-- Handles start/stop commands from DrawMethods.
-- Clears exclusive state when exclusive animation finishes.
tickAnimations
  :: AnimationState           -- ^ Animation state (for exclusive tracking)
  -> Shell                    -- ^ The shell (to look up surfaces)
  -> SurfaceDefinition        -- ^ The current surface definition
  -> [ ActiveAnim ]             -- ^ Currently active animations
  -> Map Int Int              -- ^ Current periodic timers
  -> Int                      -- ^ Delta time in ms (e.g., 50)
  -> IO ( [ ActiveAnim ], Map Int Int, Bool ) -- ^ (New active list, New timers, Needs redraw)
tickAnimations animState _shell surfDef activeAnims currentTimers delta = do
  -- 1. Update existing animations and collect commands
  ( updatedAnims, changed, commands ) <- updateActiveAnims activeAnims delta

  -- 2. Check if exclusive animation finished
  mExcl <- readIORef (asExclusiveAnim animState)
  case mExcl of
    Just exclId -> do
      let stillRunning = any (\a -> animId (aaDef a) == exclId) updatedAnims
      unless stillRunning $ writeIORef (asExclusiveAnim animState) Nothing
    Nothing     -> return ()

  -- 3. Execute commands (start/stop other animations)
  animsAfterCmds <- executeCommands surfDef updatedAnims commands

  -- 4. Process queued animations (if exclusive finished)
  animsAfterQueue <- processQueue animState surfDef animsAfterCmds

  -- 5. Check intervals to start new animations
  -- Only check intervals for animations that aren't already running (unless allowed overlap)
  let runningIds = map (animId . aaDef) animsAfterQueue
      candidates = filter (\a -> animId a `notElem` runningIds) (sdAnimations surfDef)

  ( finalAnims, finalTimers, newStarted )
    <- foldM (checkInterval delta) ( animsAfterQueue, currentTimers, False ) candidates

  -- 6. Add enabled bind animations
  enabledBinds <- readIORef (asBindState animState)
  let bindCandidates
        = filter (\a -> isBindInterval (animInterval a)
                  && animId a `Set.member` enabledBinds
                  && animId a `notElem` map (animId . aaDef) finalAnims) (sdAnimations surfDef)
  bindAnims <- catMaybes <$> mapM (`startAnimation` True) bindCandidates
  let animsWithBinds = finalAnims ++ bindAnims

  let cmdStarted   = length animsAfterCmds > length updatedAnims
      queueStarted = length animsAfterQueue > length animsAfterCmds
      bindStarted  = not (null bindAnims)
  return
    ( animsWithBinds
    , finalTimers
    , changed || newStarted || cmdStarted || queueStarted || bindStarted
    )
  where
    -- Check if an animation should start based on its interval
    checkInterval :: Int
                  -> ( [ ActiveAnim ], Map Int Int, Bool )
                  -> Animation
                  -> IO ( [ ActiveAnim ], Map Int Int, Bool )
    checkInterval dt ( accAnims, accTimers, started ) anim = do
      ( shouldStart, newTimers ) <- case animInterval anim of
        IntervalAlways -> return ( True, accTimers )
        IntervalRunonce -> return ( False, accTimers ) -- Handled at init
        IntervalNever -> return ( False, accTimers )
        IntervalRandom n -> do
          -- 1 in n chance per second.
          -- If dt is 50ms, that's 20 ticks per second.
          -- Probability per tick = 1 / (n * 20) roughly?
          -- Standard logic: 1/n chance per SECOND.
          -- So per tick (50ms), prob is 1 / (n * (1000/dt))
          let ticksPerSec = 1000.0 / fromIntegral dt :: Double
              chance      = 1.0 / (fromIntegral n * ticksPerSec)
          r <- randomRIO ( 0.0, 1.0 ) :: IO Double
          return ( r < chance, accTimers )
        IntervalPeriodic n -> do
          -- N seconds interval
          let aid     = animId anim
              current = Map.findWithDefault 0 aid accTimers
              next    = current + dt
              limit   = n * 1000
          if next >= limit
            then return ( True, Map.insert aid 0 accTimers ) -- Reset timer and start
            else return ( False, Map.insert aid next accTimers ) -- Update timer
        IntervalSometimes       -- 1/2 per sec
          -> do
            let ticksPerSec = 1000.0 / fromIntegral dt
                chance      = 1.0 / (2.0 * ticksPerSec)
            r <- randomRIO ( 0.0, 1.0 ) :: IO Double
            return ( r < chance, accTimers )
        IntervalRarely       -- 1/4 per sec
          -> do
            let ticksPerSec = 1000.0 / fromIntegral dt
                chance      = 1.0 / (4.0 * ticksPerSec)
            r <- randomRIO ( 0.0, 1.0 ) :: IO Double
            return ( r < chance, accTimers )
        IntervalBind -> return ( False, accTimers ) -- Handled by bind system
        _ -> return ( False, accTimers ) -- Others not implemented yet

      if shouldStart
        then do
          -- Create new active animation
          case animPatterns anim of
            [] -> return ( accAnims, newTimers, started )
            ( firstPat : _ ) -> do
              let isLooping = animInterval anim == IntervalAlways
                  baseWait  = apWait firstPat

              actualWait <- case apWaitMax firstPat of
                Just maxW -> randomRIO ( baseWait, maxW )
                Nothing   -> return baseWait

              let newAnim
                    = ActiveAnim { aaDef       = anim
                                 , aaStepIndex = 0
                                 , aaWaitLeft  = actualWait
                                 , aaVisual    = apSurfaceId firstPat >= 0 -- -1 means hidden/none
                                 , aaLooping   = isLooping
                                 }
              return ( accAnims ++ [ newAnim ], newTimers, True )
        else return ( accAnims, newTimers, started )

-- | Check if interval is bind type
isBindInterval :: AnimationInterval -> Bool
isBindInterval IntervalBind = True
isBindInterval (IntervalCombined intervals) = any isBindInterval intervals
isBindInterval _ = False

-- | Execute animation commands (start/stop other animations).
executeCommands :: SurfaceDefinition -> [ ActiveAnim ] -> [ AnimCommand ] -> IO [ ActiveAnim ]
executeCommands surfDef = foldM execCmd
  where
    execCmd acc cmd = case cmd of
      CmdStart aid     -> do
        let runningIds = map (animId . aaDef) acc
        if aid `elem` runningIds
          then return acc
          else case findAnimById aid surfDef of
            Nothing   -> return acc
            Just anim -> do
              mNew <- startAnimation anim False
              case mNew of
                Nothing      -> return acc
                Just newAnim -> return (acc ++ [ newAnim ])

      CmdStop aid      -> return $ filter (\a -> animId (aaDef a) /= aid) acc

      CmdStartAll aids -> do
        let runningIds = map (animId . aaDef) acc
            toStart    = filter (`notElem` runningIds) aids
        newAnims <- catMaybes <$> mapM (\aid -> case findAnimById aid surfDef of
                                          Nothing   -> return Nothing
                                          Just anim -> startAnimation anim False) toStart
        return (acc ++ newAnims)

      CmdStopAll aids  -> return $ filter (\a -> animId (aaDef a) `notElem` aids) acc

    findAnimById :: Int -> SurfaceDefinition -> Maybe Animation
    findAnimById aid sd = case filter (\a -> animId a == aid) (sdAnimations sd) of
      []      -> Nothing
      (x : _) -> Just x

-- | Update list of active animations.
-- Returns (Updated List, Did Visual State Change, Commands to execute)
-- Also handles looping for Always-interval animations.
updateActiveAnims :: [ ActiveAnim ] -> Int -> IO ( [ ActiveAnim ], Bool, [ AnimCommand ] )
updateActiveAnims anims delta = do
  ( newList, changes, cmds ) <- foldM step ( [], False, [] ) anims
  return ( newList, changes, cmds )
  where
    step ( acc, changed, cmds ) anim = do
      let newWait = aaWaitLeft anim - delta
      if newWait <= 0
        then do
          -- Move to next step
          let nextIndex  = aaStepIndex anim + 1
              patterns   = animPatterns (aaDef anim)
              -- Extract commands from current pattern before advancing
              currentPat = patterns !! aaStepIndex anim
              patCmds    = extractCommands (apMethod currentPat)

          if nextIndex >= length patterns
            then
              -- Animation finished - check if looping
              if aaLooping anim && not (null patterns)
                then do
                  -- Loop back to start
                  case viaNonEmpty head patterns of
                    Nothing -> return ( acc, changed || aaVisual anim, cmds ++ patCmds )
                    Just firstPat -> do
                      let baseWait = apWait firstPat
                      actualWait <- case apWaitMax firstPat of
                        Just maxW -> randomRIO ( baseWait, maxW )
                        Nothing   -> return baseWait
                      let loopedAnim
                            = anim { aaStepIndex = 0
                                   , aaWaitLeft  = actualWait
                                   , aaVisual    = apSurfaceId firstPat >= 0
                                   }
                      return ( acc ++ [ loopedAnim ], True, cmds ++ patCmds )
                else
                  -- Animation finished, remove it
                  return ( acc, changed || aaVisual anim, cmds ++ patCmds )
            else do
              -- Setup next pattern
              let nextPat  = patterns !! nextIndex
                  baseWait = apWait nextPat

              actualWait <- case apWaitMax nextPat of
                Just maxW -> randomRIO ( baseWait, maxW )
                Nothing   -> return baseWait

              let newAnim
                    = anim { aaStepIndex = nextIndex
                           , aaWaitLeft  = actualWait
                           , aaVisual    = apSurfaceId nextPat >= 0
                           }
              -- Visual state changes if we switch patterns (assuming patterns mostly differ)
              return ( acc ++ [ newAnim ], True, cmds ++ patCmds )
        else do
          -- Continue waiting
          let newAnim = anim { aaWaitLeft = newWait }
          return ( acc ++ [ newAnim ], changed, cmds )

    -- Extract animation control commands from DrawMethod
    extractCommands :: DrawMethod -> [ AnimCommand ]
    extractCommands method = case method of
      DrawStart ids -> map CmdStart ids
      DrawStop ids -> map CmdStop ids
      DrawAlternativeStart ids -> map CmdStart ids  -- For now, treat same as start
      DrawAlternativeStop ids -> map CmdStop ids
      DrawParallelStart ids -> [ CmdStartAll ids ]
      DrawParallelStop ids -> [ CmdStopAll ids ]
      _ -> []

-- | Composite active animations onto the base pixbuf.
-- Returns a NEW Pixbuf (does not modify base).
compositeAnimation :: Shell
                   -> ImageCache      -- ^ Image cache for overlay surfaces
                   -> Pixbuf.Pixbuf   -- ^ Base pixbuf
                   -> [ ActiveAnim ]    -- ^ Active animations to apply
                   -> IO (Maybe Pixbuf.Pixbuf)
compositeAnimation shell cache basePixbuf anims = do
  -- Filter visible animations and sort by ID (or z-order if available)
  -- For now just use list order (which implies start order) or definition order?
  -- Usually animations are layered by their definition order in surfaces.txt or sorted by ID.
  -- Types.Ghost has SortOrder but we'll stick to simple list order for now.
  let validAnims  = filter (\a -> aaStepIndex a < length (animPatterns (aaDef a))) anims
      sortedAnims = sortBy (comparing (animId . aaDef)) validAnims

  -- Clone base pixbuf to draw on
  mDest <- Pixbuf.pixbufCopy basePixbuf
  case mDest of
    Nothing   -> return Nothing
    Just dest -> do
      width <- Pixbuf.pixbufGetWidth dest
      height <- Pixbuf.pixbufGetHeight dest

      -- Apply each animation pattern
      foldM_ (\_ anim -> applyPattern shell cache dest width height anim) () sortedAnims

      return $ Just dest
  where
    applyPattern :: Shell -> ImageCache -> Pixbuf.Pixbuf -> Int32 -> Int32 -> ActiveAnim -> IO ()
    applyPattern shell cache dest destW destH anim = do
      let pat    = animPatterns (aaDef anim) !! aaStepIndex anim
          surfId = apSurfaceId pat
          x      = apX pat
          y      = apY pat
          method = apMethod pat

      -- surfId < 0 means no image (just wait/logic), so skip drawing
      when (surfId >= 0) $ do
        -- Load the surface image for the pattern (with caching)
        -- Animation patterns often reference surface IDs that are just raw PNG files
        -- (e.g., surface4000.png) without a corresponding surface definition.
        let surfaces = shellSurfaces shell
            cacheKey = shellPath shell <> "/surface" <> show surfId

        mPatPixbuf <- getCachedImage cache cacheKey $ do
          case findSurfaceById surfId surfaces of
            Just patSurfDef -> compositeSurface (shellPath shell) patSurfDef
            Nothing         -> loadDefaultSurface (shellPath shell) surfId

        case mPatPixbuf of
          Nothing        -> return ()
          Just patPixbuf -> do
            w <- Pixbuf.pixbufGetWidth patPixbuf
            h <- Pixbuf.pixbufGetHeight patPixbuf

            -- Check bounds
            let destX = max 0 (fromIntegral x :: Int32)
                destY = max 0 (fromIntegral y :: Int32)

            -- Composite based on method
            -- Currently only supporting Overlay (and Base as Overlay)
            -- TODO: Implement other methods like overlayfast, replace, etc.
            when (destX < destW && destY < destH) $ do
              let renderW = min w (destW - destX)
                  renderH = min h (destH - destY)

              Pixbuf.pixbufComposite
                patPixbuf
                dest
                destX
                destY
                renderW
                renderH
                (fromIntegral x)
                (fromIntegral y)
                1.0
                1.0
                Pixbuf.InterpTypeBilinear
                255

-- | Start a single animation by ID. Returns the new active animation if started.
startAnimation :: Animation -> Bool -> IO (Maybe ActiveAnim)
startAnimation anim looping = do
  let patterns = animPatterns anim
  if null patterns
    then return Nothing
    else case viaNonEmpty head patterns of
      Nothing -> return Nothing
      Just firstPat -> do
        let wait = apWait firstPat
        actualWait <- case apWaitMax firstPat of
          Just maxW -> randomRIO ( wait, maxW )
          Nothing   -> return wait
        let newAnim
              = ActiveAnim { aaDef       = anim
                           , aaStepIndex = 0
                           , aaWaitLeft  = actualWait
                           , aaVisual    = apSurfaceId firstPat >= 0
                           , aaLooping   = looping
                           }
        return (Just newAnim)

-- | Invoke all Runonce animations for a surface.
-- Should be called when the surface changes.
invokeRunonce :: SurfaceDefinition -> [ ActiveAnim ] -> IO [ ActiveAnim ]
invokeRunonce surfDef activeAnims = do
  let runningIds   = map (animId . aaDef) activeAnims
      runonceAnims = filter (isRunonceInterval . animInterval) (sdAnimations surfDef)
      candidates   = filter (\a -> animId a `notElem` runningIds) runonceAnims
  newAnims <- catMaybes <$> mapM (`startAnimation` False) candidates
  return (activeAnims ++ newAnims)
  where
    isRunonceInterval :: AnimationInterval -> Bool
    isRunonceInterval IntervalRunonce = True
    isRunonceInterval (IntervalCombined intervals) = any isRunonceInterval intervals
    isRunonceInterval _ = False

-- | Invoke all Always animations for a surface.
-- Should be called when the surface changes.
invokeAlways :: SurfaceDefinition -> [ ActiveAnim ] -> IO [ ActiveAnim ]
invokeAlways surfDef activeAnims = do
  let runningIds  = map (animId . aaDef) activeAnims
      alwaysAnims = filter (isAlwaysInterval . animInterval) (sdAnimations surfDef)
      candidates  = filter (\a -> animId a `notElem` runningIds) alwaysAnims
  newAnims <- catMaybes <$> mapM (`startAnimation` True) candidates
  return (activeAnims ++ newAnims)
  where
    isAlwaysInterval :: AnimationInterval -> Bool
    isAlwaysInterval IntervalAlways = True
    isAlwaysInterval (IntervalCombined intervals) = any isAlwaysInterval intervals
    isAlwaysInterval _ = False

-- | Manually invoke an animation by ID.
-- If the animation is already running, it will not be started again unless force is True.
invokeAnimation :: SurfaceDefinition -> [ ActiveAnim ] -> Int -> Bool -> IO [ ActiveAnim ]
invokeAnimation surfDef activeAnims animationId force = do
  let runningIds = map (animId . aaDef) activeAnims
      mAnim      = filter (\a -> animId a == animationId) (sdAnimations surfDef)
  case mAnim of
    []         -> return activeAnims
    (anim : _) -> if animationId `elem` runningIds && not force
      then return activeAnims
      else do
        -- Remove existing if force
        let filtered
              = if force
                then filter (\a -> animId (aaDef a) /= animationId) activeAnims
                else activeAnims
        mNewAnim <- startAnimation anim False
        case mNewAnim of
          Nothing      -> return filtered
          Just newAnim -> return (filtered ++ [ newAnim ])

-- | Stop an animation by ID.
stopAnimation :: [ ActiveAnim ] -> Int -> [ ActiveAnim ]
stopAnimation activeAnims animationId = filter (\a -> animId (aaDef a) /= animationId) activeAnims

-- | Stop all currently running animations.
stopAllAnimations :: [ ActiveAnim ] -> [ ActiveAnim ]
stopAllAnimations _ = []

-- | Clear all animations and periodic timers.
clearAnimations :: AnimationState -> IO ()
clearAnimations animState = do
  writeIORef (asActiveAnims animState) []
  writeIORef (asPeriodicState animState) Map.empty
  writeIORef (asExclusiveAnim animState) Nothing
  writeIORef (asAnimQueue animState) []

-- | Toggle a bind animation on/off.
-- When enabled, bind animations are rendered as part of the composite.
toggleBind :: AnimationState -> Int -> IO ()
toggleBind animState animId = do
  modifyIORef' (asBindState animState) $ \binds -> if Set.member animId binds
    then Set.delete animId binds
    else Set.insert animId binds

-- | Get the current bind state for an animation ID.
getBindState :: AnimationState -> Int -> IO Bool
getBindState animState animId = do
  binds <- readIORef (asBindState animState)
  return $ Set.member animId binds

-- | Set multiple bind states at once.
-- Takes a map of animation ID -> enabled state.
setBindState :: AnimationState -> Map Int Bool -> IO ()
setBindState animState bindMap = do
  let enabledIds = Map.keys $ Map.filter id bindMap
  writeIORef (asBindState animState) (Set.fromList enabledIds)

-- | Get all enabled bind animation IDs.
getEnabledBinds :: AnimationState -> IO (Set Int)
getEnabledBinds animState = readIORef (asBindState animState)

-- | Check if an exclusive animation is currently running.
isExclusiveRunning :: AnimationState -> IO Bool
isExclusiveRunning animState = do
  mExcl <- readIORef (asExclusiveAnim animState)
  return $ case mExcl of
    Nothing -> False
    Just _  -> True

-- | Process queued animations when exclusive animation finishes.
-- Should be called after each tick to check if queued animations can start.
processQueue :: AnimationState -> SurfaceDefinition -> [ ActiveAnim ] -> IO [ ActiveAnim ]
processQueue animState surfDef activeAnims = do
  mExcl <- readIORef (asExclusiveAnim animState)
  case mExcl of
    Just _  -> return activeAnims  -- Still running exclusive
    Nothing -> do
      queue <- readIORef (asAnimQueue animState)
      if null queue
        then return activeAnims
        else do
          -- Start all queued animations
          newAnims <- catMaybes <$> mapM (`startAnimation` False) queue
          writeIORef (asAnimQueue animState) []
          return (activeAnims ++ newAnims)

-- | Check if animation has exclusive option
hasExclusiveOption :: Animation -> Bool
hasExclusiveOption anim = any isExclusive (animOptions anim)
  where
    isExclusive (OptionExclusive _) = True
    isExclusive _ = False

-- | Invoke all YenE animations for a surface.
-- Should be called when \e tag is encountered in script.
-- If exclusive animation is running, queues instead.
invokeYenE :: AnimationState -> SurfaceDefinition -> [ ActiveAnim ] -> IO [ ActiveAnim ]
invokeYenE animState surfDef activeAnims = do
  mExcl <- readIORef (asExclusiveAnim animState)
  let runningIds = map (animId . aaDef) activeAnims
      yenEAnims  = filter (isYenEInterval . animInterval) (sdAnimations surfDef)
      candidates = filter (\a -> animId a `notElem` runningIds) yenEAnims

  case mExcl of
    Just _  -> do
      -- Queue animations instead of starting
      modifyIORef' (asAnimQueue animState) (++ candidates)
      return activeAnims
    Nothing -> do
      newAnims <- catMaybes <$> mapM (`startAnimation` False) candidates
      -- Check if any started animation is exclusive
      mapM_ (checkAndSetExclusive animState) newAnims
      return (activeAnims ++ newAnims)
  where
    isYenEInterval :: AnimationInterval -> Bool
    isYenEInterval IntervalYenE = True
    isYenEInterval (IntervalCombined intervals) = any isYenEInterval intervals
    isYenEInterval _ = False

-- | Set exclusive state if animation has exclusive option
checkAndSetExclusive :: AnimationState -> ActiveAnim -> IO ()
checkAndSetExclusive animState anim
  = when (hasExclusiveOption (aaDef anim))
  $ writeIORef (asExclusiveAnim animState) (Just (animId (aaDef anim)))

-- | Invoke talk animations for a surface.
-- Should be called when character count threshold is reached.
-- The Int parameter is the current character count.
-- Only triggers animations where (charCount `mod` talkN) == 0.
-- If exclusive animation is running, queues instead.
invokeTalk :: AnimationState -> SurfaceDefinition -> [ ActiveAnim ] -> Int -> IO [ ActiveAnim ]
invokeTalk animState surfDef activeAnims charCount = do
  mExcl <- readIORef (asExclusiveAnim animState)
  let runningIds = map (animId . aaDef) activeAnims
      talkAnims  = filter (shouldTrigger . animInterval) (sdAnimations surfDef)
      candidates = filter (\a -> animId a `notElem` runningIds) talkAnims

  case mExcl of
    Just _  -> do
      -- Queue animations instead of starting
      modifyIORef' (asAnimQueue animState) (++ candidates)
      return activeAnims
    Nothing -> do
      newAnims <- catMaybes <$> mapM (`startAnimation` False) candidates
      -- Check if any started animation is exclusive
      mapM_ (checkAndSetExclusive animState) newAnims
      return (activeAnims ++ newAnims)
  where
    shouldTrigger :: AnimationInterval -> Bool
    shouldTrigger (IntervalTalk n) = n > 0 && charCount `mod` n == 0
    shouldTrigger (IntervalCombined intervals) = any shouldTrigger intervals
    shouldTrigger _ = False
